/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import programa1.Atleta;
import programa1.Categoria;
import programa1.Competencia;
import programa1.Configuracion;
import programa1.Disciplina;
import programa1.Prueba;

/**
 * Interfaz para agregar una prueba
 *@author Usuario
 */
public class AgregarPrueba extends javax.swing.JFrame {
    ArrayList<Categoria> categorias= new ArrayList<Categoria>();
    private ArrayList<Atleta> atletas;
    private ArrayList<Competencia> competencias;
    private Configuracion config;
    private Competencia competencia;
    private Disciplina disciplina;
    
    
    
    
    /**
     * Creates new form AgregarPrueba
     */
    public AgregarPrueba() {
        initComponents();
        agregarCategoria(categorias);
        setLocationRelativeTo(null);
        cargarCaja();
    }
    /**
    * Hereda la lista de atletas
    *@param pAtletas Lista de Atletas
    */
    public void setAtletas(ArrayList<Atleta> pAtletas){
            atletas=pAtletas;
    }
  
    /**
    * Hereda la lista de competencias
    * @param pCompetencias Lista de competencias
    */
    public void setCompetencias(ArrayList<Competencia> pCompetencias){
            competencias=pCompetencias;
    }
      /**
    *Hereda la configuracion
    *@param pConfig Configuracion del sistema
    */
    public void setConfig(Configuracion pConfig){
            config = pConfig;
    }
    /**
    * Hereda la competencia y disciplina a la que pertenece esta clase
    * @param pCompetencia Competencia
    * @param pDisciplina Disciplina
    */
    public void cargar(Competencia pCompetencia,Disciplina pDisciplina){
        competencia= pCompetencia;
        disciplina=pDisciplina;
    }
    /**
    * Carga la caja de seleccion con su correspondiente información
    */
    private void cargarCaja(){
        for(Categoria i : categorias){
            cajaCategoria.addItem(i.toString());
        }
            
    }
    /**
     * Crea todas las categorias existentes y las agrega a una lista
     * @param categorias Guarda las categorias
    */
    private void agregarCategoria(ArrayList<Categoria> categorias){
        categorias.add(new Categoria("Mayor","Masculino"));
        categorias.add(new Categoria("Mayor","Femenino"));
        categorias.add(new Categoria("Master","Masculino"));
        categorias.add(new Categoria("Master","Femenino"));
        categorias.add(new Categoria("U15","Masculino"));
        categorias.add(new Categoria("U15","Femenino"));
        categorias.add(new Categoria("U18","Masculino"));
        categorias.add(new Categoria("U18","Femenino"));
        categorias.add(new Categoria("U20","Masculino"));
        categorias.add(new Categoria("U20","Femenino"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cajaCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        Ok = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cajaCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cajaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCategoriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Genero");

        jLabel2.setText("Nombre");

        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });

        Ok.setText("Agregar Prueba");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ok)
                        .addGap(18, 18, 18)
                        .addComponent(volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cajaCategoria, 0, 207, Short.MAX_VALUE)
                    .addComponent(cajaNombre))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ok)
                    .addComponent(volver))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
       String nombre=cajaNombre.getText();
       String m=cajaCategoria.getSelectedItem().toString();
       System.out.println(m);
       Prueba at = new Prueba(nombre,m);
       disciplina.getPruebas().add(at);
       dispose();
       MenuPrueba ventana = new  MenuPrueba();
       ventana.setVisible(true);
       ventana.setAtletas(atletas);
       ventana.setCompetencias(competencias);
        ventana.setConfig(config);
        ventana.cargarPanel(competencia, disciplina);
        JOptionPane.showMessageDialog(this,"Elemento agregado\n"+at.toString());
    }//GEN-LAST:event_OkActionPerformed

    private void cajaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCategoriaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
       MenuPrueba ventana = new  MenuPrueba();
       ventana.setVisible(true);
       ventana.setAtletas(atletas);
       ventana.setCompetencias(competencias);
        ventana.setConfig(config);
        ventana.cargarPanel(competencia, disciplina);
    }//GEN-LAST:event_volverActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ok;
    private javax.swing.JComboBox<String> cajaCategoria;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
