/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import programa1.Atleta;
import programa1.Categoria;
import programa1.Competencia;
import programa1.Configuracion;

/**
 * Interfaz para agregar una competencia
 *@author Usuario
 */
public class AgregarCompetencia extends javax.swing.JFrame {
    private ArrayList<Atleta> atletas;
    private ArrayList<Competencia> competencias;
    private Configuracion config;
    /**
     * Creates new form AgregarCompetencia
     */
    public AgregarCompetencia() {
        initComponents();
        setLocationRelativeTo(null);
        cargarCF();
    }
    /**
    *Hereda la configuracion
    *@param pConfig Configuracion del sistema
    */
    public void setConfig(Configuracion pConfig){
        config = pConfig;
    }
    /**
    * Carga la seleccion de fechas
    */
    private void cargarCF(){
        for(int i = 1920; i < 2023;i++){
            cajaY.addItem(""+i);
            cajaY2.addItem(""+i);
        }
        for(int i = 1; i < 13;i++){
            cajaM.addItem(""+i);
            cajaM2.addItem(""+i);
        }
        for(int i = 1; i < 32;i++){
           cajaD.addItem(""+i);
           cajaD2.addItem(""+i);
        }    
    }
    /**
    * Hereda la lista de atletas
    *@param pAtletas Lista de atletas
    */
    public void setAtletas(ArrayList<Atleta> pAtletas){
            atletas=pAtletas;
    }
    /**
    * Hereda la lista de competencias
    *@param pCompetencias Lista de competencias
    */
    public void setCompetencias(ArrayList<Competencia> pCompetencias){
            competencias=pCompetencias;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaPais = new javax.swing.JTextField();
        cajaLugar = new javax.swing.JTextField();
        cajaM = new javax.swing.JComboBox<>();
        cajaD = new javax.swing.JComboBox<>();
        cajaY = new javax.swing.JComboBox<>();
        cajaM2 = new javax.swing.JComboBox<>();
        cajaD2 = new javax.swing.JComboBox<>();
        cajaY2 = new javax.swing.JComboBox<>();
        agregarCompetencia = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Pais");

        jLabel3.setText("Lugar");

        jLabel4.setText("Fecha Inicial");

        jLabel5.setText("Fecha Final");

        cajaM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        cajaD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        cajaY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        cajaM2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        cajaD2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        cajaY2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        agregarCompetencia.setText("Agregar Competencia");
        agregarCompetencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCompetenciaActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cajaY2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cajaM2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cajaD2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cajaNombre)
                                .addComponent(cajaPais)
                                .addComponent(cajaLugar, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cajaY, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(cajaD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregarCompetencia)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cajaPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cajaLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cajaY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCompetencia)
                    .addComponent(volver))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarCompetenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCompetenciaActionPerformed
        boolean realizar=true;
        Competencia compe;   
        String nombre=cajaNombre.getText();
        String pais=cajaPais.getText();
        String lugar=cajaLugar.getText();
        int Y1=Integer.parseInt(cajaY.getSelectedItem().toString());
        int M1=Integer.parseInt(cajaM.getSelectedItem().toString());
        int D1=Integer.parseInt(cajaD.getSelectedItem().toString());
        int Y2=Integer.parseInt(cajaY2.getSelectedItem().toString());
        int M2=Integer.parseInt(cajaM2.getSelectedItem().toString());
        int D2=Integer.parseInt(cajaD2.getSelectedItem().toString());
        LocalDate fecha1,fecha2;
        fecha1=LocalDate.of(Y1,M1,D1); 
        fecha2=LocalDate.of(Y2,M2,D2); 
        boolean antes = fecha1.isBefore(fecha2);
        if(!antes){
            realizar=false;
             JOptionPane.showMessageDialog(this,"La fecha inicial es mayor a la final","Error",JOptionPane.ERROR_MESSAGE);
        }
        compe= new Competencia(nombre,config.getNumCompetencia(),pais,lugar,fecha1,fecha2);
        if(compe.getNombre()==null){
             realizar=false;
            JOptionPane.showMessageDialog(this,"No se ha podido agregar el nombre de la competencia","Error",JOptionPane.ERROR_MESSAGE);
        }
        if(compe.getLugar()==null){
             realizar=false;
            JOptionPane.showMessageDialog(this,"No se ha podido agregar el nombre del lugar de la competencia","Error",JOptionPane.ERROR_MESSAGE);
        }
        if (realizar){
            JOptionPane.showMessageDialog(this,"Competencia Agregada"+compe.toString());
            competencias.add(compe);
            config.sumar();
            dispose();
            MenuCompetencia ventana = new MenuCompetencia();
            ventana.setVisible(true);
            ventana.setAtletas(atletas);
            ventana.setCompetencias(competencias);
            ventana.setConfig(config);
            
        }
    }//GEN-LAST:event_agregarCompetenciaActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
        MenuCompetencia ventana = new MenuCompetencia();
        ventana.setVisible(true);
        ventana.setAtletas(atletas);
        ventana.setCompetencias(competencias);
        ventana.setConfig(config);
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCompetencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCompetencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCompetencia;
    private javax.swing.JComboBox<String> cajaD;
    private javax.swing.JComboBox<String> cajaD2;
    private javax.swing.JTextField cajaLugar;
    private javax.swing.JComboBox<String> cajaM;
    private javax.swing.JComboBox<String> cajaM2;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaPais;
    private javax.swing.JComboBox<String> cajaY;
    private javax.swing.JComboBox<String> cajaY2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
