/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import programa1.Atleta;
import programa1.Competencia;
import programa1.Configuracion;
import programa1.Disciplina;
import programa1.Marca;
import programa1.Prueba;

/**
 *Registra marcas
 * @author Usuario
 */
public class RegistrarMarca extends javax.swing.JFrame {
    private ArrayList<Atleta> atletas;
    private ArrayList<Competencia> competencias;
    private Configuracion config;
    private Competencia competencia;
    private Prueba prueba;
    private Disciplina disciplina;


    /**
     * Creates new form RegistrarMarca
     */
    public RegistrarMarca() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    /**
    * Hereda la lista de atletas
    *@param pAtletas Lista de Atletas
    */
    public void setAtletas(ArrayList<Atleta> pAtletas){
            atletas=pAtletas;
    }
    /**
    *Hereda la lista de competencias
    *@param pCompetencias Lista de competencias
    */
    public void setCompetencias(ArrayList<Competencia> pCompetencias){
            competencias=pCompetencias;
    }
    /**
    *Hereda la configuracion
    *@param pConfig Configuracion del sistema
    */
    public void setConfig(Configuracion pConfig){
        config = pConfig;
        
        
    }/**
    *Hereda la competencia, Disciplina y prueba a la que pertenece esta clase y carga las cajas de seleccion
    *@param pCompetencia Competencia
    * @param pDisciplina Disciplina
    * @param pPrueba Prueba
    */
    public void cargarPanel(Competencia pCompetencia, Prueba pPrueba,Disciplina pDisciplina){
        competencia = pCompetencia;
        for(Atleta i : competencia.getAtletlas()){
            eAtleta.addItem(i.getNombreCompleto());
        }
        prueba= pPrueba;
        disciplina=pDisciplina;
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eAtleta = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        regi = new javax.swing.JButton();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eAtleta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel1.setText("Atleta");

        jLabel2.setText("Marca");

        regi.setText("Registrar Marca");
        regi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regiActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regi)
                        .addGap(18, 18, 18)
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(eAtleta, 0, 196, Short.MAX_VALUE)
                        .addComponent(marca)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regi)
                    .addComponent(volver))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    *Busca el atleta que fue seleccionado en la casilla de texto y lo retorna
    * @param copy Identificador utilizado para encontrar el elemento deseado
    */
    private Atleta buscarAtleta(String copy){
        int contador=0;
        boolean encontrado=false;
        while (contador< competencia.getAtletlas().size()&&!encontrado){
            if (competencia.getAtletlas().get(contador).getNombreCompleto().equals(copy)) {
                contador=contador;
                encontrado=true;
            }
            else{
               contador++;
            }
        }
        return competencia.getAtletlas().get(contador);
    }
    
    private void regiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regiActionPerformed
        boolean realizar= true;
        int posicion=0;
        String copy=eAtleta.getSelectedItem().toString();
        String m=marca.getText();
        String me= disciplina.getMedida();
        Atleta at = buscarAtleta(copy);
        int mar=0;
        try{
            mar=Integer.parseInt(m);
        }
        catch(NumberFormatException e){
            realizar=false;
            JOptionPane.showMessageDialog(this,"La marca debe ser un número entero","Error",JOptionPane.ERROR_MESSAGE);
        }
        System.out.println(me.equals("m"));
  
        if(realizar){
            while (posicion< prueba.getMarcas().size()&&!realizar){
                if (me.equals("m")){
                    if(prueba.getMarcas().get(posicion).getMarca()> mar){
                        realizar=true;
                    }
                    else{
                       posicion++;
                    }
                }
                else if (me.equals("s")){
                    if(prueba.getMarcas().get(posicion).getMarca()< mar){
                        realizar=true;
                    }
                    else{
                       posicion++;
                    }
                }
                else{
                    posicion++;
                }
            }
            Marca marcaT= new Marca(at.getNombreCompleto(),mar,at.getPaisOrigen(),posicion+1,competencia.getNombre(),prueba.toString(),Integer.parseInt(at.getIdAtleta()),me);
            prueba.getMarcas().add(posicion,marcaT);
            posicion++;
            for (int i =posicion;i<prueba.getMarcas().size();i++){
                prueba.getMarcas().get(posicion).aumentarPosicion();
            }
            posicion=0;
            while (posicion< at.getMarcas().size()&&!realizar){
                if (me.equals(at.getMarcas().get(posicion).getMedida())&& me.equals("m")){
                    if(at.getMarcas().get(posicion).getMarca()< mar){
                        realizar=true;
                    }
                    else{
                       posicion++;
                    }
                }
                
                else if (me.equals(at.getMarcas().get(posicion).getMedida())&& me.equals("s")){
                    if(at.getMarcas().get(posicion).getMarca()> mar){
                        realizar=true;
                    }
                    else{
                       posicion++;
                    }
                }
                
                else{
                    posicion++;
                }
            }
            at.getMarcas().add(posicion, marcaT);
            JOptionPane.showMessageDialog(this,"Marca registrada");
            dispose();
            MenuPrueba ventana = new  MenuPrueba();
            ventana.setVisible(true);
            ventana.setAtletas(atletas);
            ventana.setCompetencias(competencias);
            ventana.setConfig(config);
            ventana.cargarPanel(competencia, disciplina);
       
        }
    }//GEN-LAST:event_regiActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
        MenuDisciplina ventana = new MenuDisciplina();
        ventana.setVisible(true);
        ventana.setAtletas(atletas);
        ventana.setCompetencias(competencias);
        ventana.setConfig(config);
        ventana.cargarPanel(competencia);
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarMarca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarMarca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> eAtleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField marca;
    private javax.swing.JButton regi;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
