/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.programa2;

import futoshiki.Futoshiki;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia S.R.S
 */
public class SettingsInter extends javax.swing.JFrame {
    private ArrayList<Futoshiki> futoshiki;
    private int aXa=0;
    /**
     * Creates new form SettingsInter
     */
    private boolean aparece;
    
    public SettingsInter() {
        initComponents();
        this.getContentPane().setBackground(Color.getHSBColor(90, 130, 180));
        jPanel2.setBackground(Color.getHSBColor(90, 130, 180));
        
        
        
    }
    public void setGame(ArrayList<Futoshiki> pFutoshiki, int pAxa){
        futoshiki=pFutoshiki;
        aXa=pAxa;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jRFac = new javax.swing.JRadioButton();
        jRInt = new javax.swing.JRadioButton();
        jRDif = new javax.swing.JRadioButton();
        jRSi = new javax.swing.JRadioButton();
        jRNo = new javax.swing.JRadioButton();
        jRTimer = new javax.swing.JRadioButton();
        jRDer = new javax.swing.JRadioButton();
        jRIzq = new javax.swing.JRadioButton();
        labelNivel = new javax.swing.JLabel();
        labelReloj = new javax.swing.JLabel();
        labelNivel2 = new javax.swing.JLabel();
        jLabelConf = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRFac);
        jRFac.setText("Fácil");
        jRFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFacActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRInt);
        jRInt.setText("Intermedio");
        jRInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRIntActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRDif);
        jRDif.setText("Difícil");
        jRDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDifActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRSi);
        jRSi.setText("Si");
        jRSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSiActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRNo);
        jRNo.setText("No");
        jRNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNoActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRTimer);
        jRTimer.setText("Timer");
        jRTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTimerActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRDer);
        jRDer.setText("Derecha");
        jRDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDerActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRIzq);
        jRIzq.setText("Izquierda");
        jRIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRIzqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRIzq)
                    .addComponent(jRDer)
                    .addComponent(jRTimer)
                    .addComponent(jRNo)
                    .addComponent(jRSi)
                    .addComponent(jRDif)
                    .addComponent(jRInt)
                    .addComponent(jRFac))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jRFac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRDif)
                .addGap(70, 70, 70)
                .addComponent(jRSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRTimer)
                .addGap(90, 90, 90)
                .addComponent(jRDer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRIzq)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        labelNivel.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        labelNivel.setText("1. Nivel");

        labelReloj.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        labelReloj.setText("2. Reloj:");

        labelNivel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        labelNivel2.setText("3. Posición en la ventana del panel de dígitos:");

        jLabelConf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelConf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConf.setText("    ------<->--<->- CONFIGURACIÓN-<->--<->------");
        jLabelConf.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelReloj)
                            .addComponent(labelNivel)
                            .addComponent(labelNivel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(0, 15, Short.MAX_VALUE))
            .addComponent(jLabelConf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNivel)
                        .addGap(133, 133, 133)
                        .addComponent(labelReloj)
                        .addGap(115, 115, 115)
                        .addComponent(labelNivel2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRFacActionPerformed

    private void jRIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRIntActionPerformed

    private void jRDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRDifActionPerformed

    private void jRSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSiActionPerformed
        aparece=true;
    }//GEN-LAST:event_jRSiActionPerformed

    private void jRNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNoActionPerformed
        aparece=false;
        
    }//GEN-LAST:event_jRNoActionPerformed

    private void jRTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTimerActionPerformed

    private void jRDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRDerActionPerformed

    private void jRIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRIzqActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        if(validar()==true){
            InitialScreen initialScreen = new InitialScreen();
            initialScreen.setVisible(true);
            initialScreen.setReloj(aparece);
            initialScreen.setGame(futoshiki,aXa);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos una de las opciones de cada requerimiento indicado");
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    
    public void setReloj(boolean r){
        aparece=r;
    }
    
    private boolean validar(){
        if(jRNo.isSelected()||jRSi.isSelected()||jRTimer.isSelected()){
            return true;
        }  
        if(jRFac.isSelected()||jRInt.isSelected()||jRDif.isSelected()){
            return true;
        }
        if(jRDer.isSelected()||jRIzq.isSelected()){
            return true;
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsInter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabelConf;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRDer;
    private javax.swing.JRadioButton jRDif;
    private javax.swing.JRadioButton jRFac;
    private javax.swing.JRadioButton jRInt;
    private javax.swing.JRadioButton jRIzq;
    private javax.swing.JRadioButton jRNo;
    private javax.swing.JRadioButton jRSi;
    private javax.swing.JRadioButton jRTimer;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelNivel2;
    private javax.swing.JLabel labelReloj;
    // End of variables declaration//GEN-END:variables
}
