/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Configuracion;
import Modelo.Futoshiki;
import Modelo.Model;
import controlador.Controlador;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Natalia S.R.S
 */
public class InitialScreen extends javax.swing.JFrame {
    private ArrayList<Futoshiki> futoshiki;
    private Configuracion confi;
    /**
     * Creates new form InitialScreen
     */
    
    ////FondoPanel fondo = new FondoPanel();
    
    private boolean aparece;
    public void setGame(ArrayList<Futoshiki> pFutoshiki, Configuracion pConfi){
        futoshiki=pFutoshiki;
        confi=pConfi;
    }
    public InitialScreen() {
        
        ////this.setContentPane(fondo);
        initComponents();
        this.getContentPane().setBackground(Color.getHSBColor(90, 130, 180));
        ///this.getContentPane().setBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnAD = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lSignos2 = new javax.swing.JLabel();
        lSignos1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 102, 153));
        nameLabel.setText("FUTOSHIKI");
        nameLabel.setToolTipText("");
        nameLabel.setFocusable(false);
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnJugar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnJugar.setText("JUGAR");
        btnJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJugarMouseClicked(evt);
            }
        });
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        btnConfig.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnConfig.setText("Configurar");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnAD.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnAD.setText("Acerca de");
        btnAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lSignos2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lSignos2.setForeground(new java.awt.Color(255, 255, 255));
        lSignos2.setText("-<->--<->----");

        lSignos1.setBackground(new java.awt.Color(255, 255, 255));
        lSignos1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lSignos1.setForeground(new java.awt.Color(255, 255, 255));
        lSignos1.setText("----<->--<->-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAD, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lSignos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSignos2)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSignos2)
                    .addComponent(lSignos1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        Interface interfaz = new Interface();
        interfaz.setNivel(confi.getNivel());
        if(confi.getMultiNivel()){
            interfaz.setNivel("facil");
        }
        interfaz.setIzquierda(confi.getIzquierda());
        interfaz.setAXa(confi.getAXa());
        
        Model modelo=new Model(interfaz.getContentPane(),interfaz.getTxtNombre(),interfaz.getLevelLabel());
        modelo.setLabH(interfaz.getLabH());
        modelo.setLabS(interfaz.getLabS());
        modelo.setLabM(interfaz.getLabM());
        modelo.setlCronometer(interfaz.getlCronometer());
        modelo.setReloj(aparece);
        modelo.setGame(futoshiki,confi);
        interfaz.setVisible(true);
        Controlador controlador=new Controlador(interfaz,modelo);
        this.dispose();        
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        String url = "C:\\Users\\Natalia S.R.S\\OneDrive\\Desktop\\MANUAL DE USUARIO_V2.pdf";
        ProcessBuilder p = new ProcessBuilder();
        p.command("cmd.exe", "/c", url);
        try {
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(InitialScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Este programa corresponde al juego llamado FUTOSHIKI, creado el 10 de noviembre del 2022, por los estudiantes: Brandon Andrés Mora Díaz, 2022164409 y Natalia Sofía Rodríguez Solano, 2021033307", 
                "ACERCA DE", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnADActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJugarMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_btnJugarMouseClicked

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
        SettingsInter  settingsInter= new SettingsInter();
        settingsInter.setVisible(true);
        settingsInter.setGame(futoshiki,confi);
        this.dispose();
    }//GEN-LAST:event_btnConfigActionPerformed

    
    public void setReloj(boolean r){
        aparece=r;
    }
    
    
    
    /*public Icon icono(String path, int width, int heigth){
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage()
                    .getScaledInstance(width, heigth, java.awt.Image.SCALE_SMOOTH));
        return img;
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAD;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lSignos1;
    private javax.swing.JLabel lSignos2;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
