/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Configuracion;
import Modelo.Futoshiki;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia S.R.S
 */
public class SettingsInter extends javax.swing.JFrame {
    private ArrayList<Futoshiki> futoshiki;
    private Configuracion confi;
    /**
     * Creates new form SettingsInter
     */
    private boolean aparece;    
    public SettingsInter() {
        initComponents();
        this.getContentPane().setBackground(Color.getHSBColor(90, 130, 180));
        jPanel2.setBackground(Color.getHSBColor(90, 130, 180));
    }
    public void setGame(ArrayList<Futoshiki> pFutoshiki, Configuracion pConfi){
        futoshiki=pFutoshiki;
        confi=pConfi;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabelConf = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        labelNivel = new javax.swing.JLabel();
        labelReloj = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRFac = new javax.swing.JRadioButton();
        jRInt = new javax.swing.JRadioButton();
        jRDif = new javax.swing.JRadioButton();
        jRSi = new javax.swing.JRadioButton();
        jRNo = new javax.swing.JRadioButton();
        jRTimer = new javax.swing.JRadioButton();
        jRDer = new javax.swing.JRadioButton();
        jRIzq = new javax.swing.JRadioButton();
        jR5 = new javax.swing.JRadioButton();
        jR6 = new javax.swing.JRadioButton();
        jR7 = new javax.swing.JRadioButton();
        jR9 = new javax.swing.JRadioButton();
        jR8 = new javax.swing.JRadioButton();
        jRSi1 = new javax.swing.JRadioButton();
        jRNo1 = new javax.swing.JRadioButton();
        labelNivel2 = new javax.swing.JLabel();
        labelMulti = new javax.swing.JLabel();
        labelNivel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelConf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelConf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConf.setText("    ------<->--<->- CONFIGURACIÓN-<->--<->------");
        jLabelConf.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        labelNivel.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        labelNivel.setText("1. Nivel");

        labelReloj.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        labelReloj.setText("2. Reloj:");

        jPanel2.setOpaque(false);

        jRFac.setText("Fácil");
        jRFac.setOpaque(false);
        jRFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRFacActionPerformed(evt);
            }
        });

        jRInt.setText("Intermedio");
        jRInt.setOpaque(false);
        jRInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRIntActionPerformed(evt);
            }
        });

        jRDif.setText("Difícil");
        jRDif.setOpaque(false);
        jRDif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDifActionPerformed(evt);
            }
        });

        jRSi.setText("Si");
        jRSi.setOpaque(false);
        jRSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSiActionPerformed(evt);
            }
        });

        jRNo.setText("No");
        jRNo.setOpaque(false);
        jRNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNoActionPerformed(evt);
            }
        });

        jRTimer.setText("Timer");
        jRTimer.setOpaque(false);
        jRTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTimerActionPerformed(evt);
            }
        });

        jRDer.setText("Derecha");
        jRDer.setOpaque(false);
        jRDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRDerActionPerformed(evt);
            }
        });

        jRIzq.setText("Izquierda");
        jRIzq.setOpaque(false);
        jRIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRIzqActionPerformed(evt);
            }
        });

        jR5.setText("5");
        jR5.setOpaque(false);
        jR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR5ActionPerformed(evt);
            }
        });

        jR6.setText("6");
        jR6.setOpaque(false);
        jR6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR6ActionPerformed(evt);
            }
        });

        jR7.setText("7");
        jR7.setOpaque(false);
        jR7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR7ActionPerformed(evt);
            }
        });

        jR9.setText("9");
        jR9.setOpaque(false);
        jR9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR9ActionPerformed(evt);
            }
        });

        jR8.setText("8");
        jR8.setOpaque(false);
        jR8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR8ActionPerformed(evt);
            }
        });

        jRSi1.setText("Si");
        jRSi1.setOpaque(false);
        jRSi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRSi1ActionPerformed(evt);
            }
        });

        jRNo1.setText("No");
        jRNo1.setOpaque(false);
        jRNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRNo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRIzq)
                    .addComponent(jRDer)
                    .addComponent(jRTimer)
                    .addComponent(jRNo)
                    .addComponent(jRSi)
                    .addComponent(jRDif)
                    .addComponent(jRInt)
                    .addComponent(jRFac)
                    .addComponent(jR5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jR6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jR7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jR9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jR8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRSi1)
                    .addComponent(jRNo1))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jRFac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRDif)
                .addGap(40, 40, 40)
                .addComponent(jRSi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRTimer)
                .addGap(30, 30, 30)
                .addComponent(jRDer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRIzq)
                .addGap(33, 33, 33)
                .addComponent(jR5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jR6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jR7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jR8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jR9)
                .addGap(18, 18, 18)
                .addComponent(jRSi1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRNo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelNivel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        labelNivel2.setText("3. Posición en la ventana del panel de dígitos:");

        labelMulti.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        labelMulti.setText("5. Multinivel:");

        labelNivel4.setFont(new java.awt.Font("Rockwell Condensed", 1, 12)); // NOI18N
        labelNivel4.setText("4. Tamaño de la cuadrícula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelConf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNivel2)
                                .addGap(164, 164, 164))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelNivel)
                                    .addGap(357, 357, 357))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelReloj)
                                    .addGap(340, 340, 340)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(labelNivel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(labelMulti)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAceptar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(114, 114, 114)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelNivel)
                        .addGap(85, 85, 85)
                        .addComponent(labelReloj)
                        .addGap(91, 91, 91)
                        .addComponent(labelNivel2)
                        .addGap(100, 100, 100)
                        .addComponent(labelNivel4)
                        .addGap(129, 129, 129)
                        .addComponent(labelMulti)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        
        if(validar()==true){
            InitialScreen initialScreen = new InitialScreen();
            initialScreen.setVisible(true);
            initialScreen.setReloj(aparece);
            initialScreen.setGame(futoshiki,confi);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos una de las opciones de cada requerimiento indicado");
        }
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jRFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRFacActionPerformed
        confi.setNivel("facil");       
        System.out.println(confi.getNivel());
    }//GEN-LAST:event_jRFacActionPerformed

    private void jRIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRIntActionPerformed
        confi.setNivel("intermedio");       
        System.out.println(confi.getNivel());
    }//GEN-LAST:event_jRIntActionPerformed

    private void jRDifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDifActionPerformed
        confi.setNivel("dificil");       
        System.out.println(confi.getNivel());
    }//GEN-LAST:event_jRDifActionPerformed

    private void jRSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSiActionPerformed
        //aparece=true;
    }//GEN-LAST:event_jRSiActionPerformed

    private void jRNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNoActionPerformed
        //aparece=false;
    }//GEN-LAST:event_jRNoActionPerformed

    private void jRTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTimerActionPerformed

    private void jRDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRDerActionPerformed
        confi.setIzquierda(false);
    }//GEN-LAST:event_jRDerActionPerformed

    private void jRIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRIzqActionPerformed
        confi.setIzquierda(true);
    }//GEN-LAST:event_jRIzqActionPerformed

    private void jR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR5ActionPerformed
        confi.setAXa(5);
        System.out.println(confi.getAXa());
    }//GEN-LAST:event_jR5ActionPerformed

    private void jR6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR6ActionPerformed
        confi.setAXa(6);
        System.out.println(confi.getAXa());
    }//GEN-LAST:event_jR6ActionPerformed

    private void jR7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR7ActionPerformed
        confi.setAXa(7);
        System.out.println(confi.getAXa());
    }//GEN-LAST:event_jR7ActionPerformed

    private void jR9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR9ActionPerformed
        confi.setAXa(9);
        System.out.println(confi.getAXa());
    }//GEN-LAST:event_jR9ActionPerformed

    private void jR8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR8ActionPerformed
        confi.setAXa(8);
        System.out.println(confi.getAXa());
    }//GEN-LAST:event_jR8ActionPerformed

    private void jRSi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRSi1ActionPerformed
        confi.setMultiNivel(true);
        System.out.println(confi.getMultiNivel());
    }//GEN-LAST:event_jRSi1ActionPerformed

    private void jRNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRNo1ActionPerformed
        confi.setMultiNivel(false);
        System.out.println(confi.getMultiNivel());
    }//GEN-LAST:event_jRNo1ActionPerformed

    
    public void setReloj(boolean r){
        aparece=r;
    }
    
    private boolean validar(){
        if(jRNo.isSelected()||jRSi.isSelected()||jRTimer.isSelected()){
            return true;
        }          
        if(jRFac.isSelected()||jRInt.isSelected()||jRDif.isSelected()){
            return true;
        }
        if(jRDer.isSelected()||jRIzq.isSelected()){
            return true;
        }
        
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsInter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabelConf;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jR5;
    private javax.swing.JRadioButton jR6;
    private javax.swing.JRadioButton jR7;
    private javax.swing.JRadioButton jR8;
    private javax.swing.JRadioButton jR9;
    private javax.swing.JRadioButton jRDer;
    private javax.swing.JRadioButton jRDif;
    private javax.swing.JRadioButton jRFac;
    private javax.swing.JRadioButton jRInt;
    private javax.swing.JRadioButton jRIzq;
    private javax.swing.JRadioButton jRNo;
    private javax.swing.JRadioButton jRNo1;
    private javax.swing.JRadioButton jRSi;
    private javax.swing.JRadioButton jRSi1;
    private javax.swing.JRadioButton jRTimer;
    private javax.swing.JLabel labelMulti;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelNivel2;
    private javax.swing.JLabel labelNivel4;
    private javax.swing.JLabel labelReloj;
    // End of variables declaration//GEN-END:variables
}
